create table if not exists themes (
  id text primary key,
  name text not null,
  aliases text[] not null default '{}',
  keywords text[] not null default '{}',
  supply_chain text[] not null default '{}',
  core_variables text[] not null default '{}',
  private_segments text[] not null default '{}',
  counter_indicators text[] not null default '{}',
  theme_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists evidence_items (
  id text primary key,
  source text not null,
  url text not null,
  title text not null,
  published_at timestamptz,
  theme_id text references themes(id) on delete set null,
  extracted_claims text[] not null default '{}',
  relevance_score numeric not null default 0,
  embedding jsonb,
  evidence_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists signal_cards (
  id text primary key,
  theme_id text not null,
  date date not null,
  rank integer not null,
  confidence numeric not null,
  signal_json jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists feedback (
  id bigint generated by default as identity primary key,
  signal_id text not null references signal_cards(id) on delete cascade,
  label text not null check (label in ('useful', 'wrong', 'watch', 'investable', 'ignore')),
  note text,
  created_at timestamptz not null default now()
);

create table if not exists eval_results (
  signal_id text primary key references signal_cards(id) on delete cascade,
  forward_return_30d numeric,
  forward_return_90d numeric,
  forward_return_180d numeric,
  evidence_confirmed boolean,
  human_label text check (human_label in ('useful', 'wrong', 'watch', 'investable', 'ignore')),
  eval_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists signal_cards_theme_date_idx on signal_cards(theme_id, date);
create index if not exists signal_cards_date_rank_idx on signal_cards(date, rank);
create index if not exists signal_cards_confidence_idx on signal_cards(confidence desc);
create index if not exists evidence_items_theme_source_idx on evidence_items(theme_id, source);
create index if not exists feedback_signal_created_idx on feedback(signal_id, created_at desc);
